# Supported ATen operators and their default inputs
aten._adaptive_avg_pool2d.default: torchbench_train/vgg16_training.json
aten._adaptive_avg_pool2d_backward.default: torchbench_train/vgg16_training.json
aten._cudnn_rnn.default: torchbench_train/tts_angular_training.json
aten._cudnn_rnn_backward.default: torchbench_train/tts_angular_training.json
aten._embedding_bag.default: torchbench_train/fambench_dlrm_training.json
aten._embedding_bag_per_sample_weights_backward.default: torchbench_train/fambench_dlrm_training.json
aten._fft_c2c.default: hf_train/GoogleFnet_training.json
aten._index_put_impl_.default: torchbench_train/vision_maskrcnn_training.json
aten._log_softmax.default: torchbench_train/pytorch_struct_training.json
aten._log_softmax_backward_data.default: torchbench_train/pytorch_struct_training.json
aten._softmax.default: torchbench_train/timm_vision_transformer_training.json
aten._softmax_backward_data.default: torchbench_train/timm_vision_transformer_training.json
aten._sparse_coo_tensor_with_dims_and_tensors.default: torchbench_train/fambench_dlrm_training.json
aten._to_copy.default: torchbench_train/Super_SloMo_training.json
aten._unsafe_view.default: torchbench_train/timm_vision_transformer_training.json
aten.abs.default: torchbench_train/Super_SloMo_training.json
aten.add.Scalar: torchbench_train/timm_efficientdet_training.json
aten.add.Tensor: torchbench_train/mobilenet_v3_large_training.json
aten.add_.Tensor: torchbench_train/mobilenet_v3_large_training.json
aten.addcmul.default: timm_train/resmlp_12_224_training.json
aten.addmm.default: torchbench_train/mobilenet_v3_large_training.json
aten.any.default: torchbench_train/hf_Bart_training.json
aten.as_strided_.default: timm_train/jx_nest_base_training.json
aten.avg_pool2d.default: torchbench_train/timm_nfnet_training.json
aten.avg_pool2d_backward.default: torchbench_train/timm_nfnet_training.json
aten.bernoulli_.float: timm_train/jx_nest_base_training.json
aten.bitwise_and.Tensor: torchbench_train/vision_maskrcnn_training.json
aten.bitwise_not.default: hf_train/DebertaV2ForQuestionAnswering_training.json
aten.bitwise_xor.Tensor: torchbench_train/fastNLP_Bert_training.json
aten.bmm.default: torchbench_train/fambench_dlrm_training.json
aten.cat.default: torchbench_train/fambench_dlrm_training.json
aten.clamp.default: torchbench_train/vision_maskrcnn_training.json
aten.clamp_min.default: torchbench_train/tts_angular_training.json
aten.clone.default: torchbench_train/mobilenet_v3_large_training.json
aten.col2im.default: timm_train/volo_d1_224_training.json
aten.col2im_backward.default: timm_train/volo_d1_224_training.json
aten.constant_pad_nd.default: torchbench_train/timm_nfnet_training.json
aten.convolution.default: torchbench_train/mobilenet_v3_large_training.json
aten.convolution_backward.default: torchbench_train/mobilenet_v3_large_training.json
aten.copy_.default: torchbench_train/mobilenet_v3_large_training.json
aten.cos.default: hf_train/XLNetLMHeadModel_training.json
aten.cumsum.default: torchbench_train/hf_Longformer_training.json
aten.div.Scalar: torchbench_train/mobilenet_v3_large_training.json
aten.div.Tensor: torchbench_train/mobilenet_v3_large_training.json
aten.div_.Tensor: torchbench_train/hf_Longformer_training.json
aten.elu.default: torchbench_train/nvidia_deeprecommender_training.json
aten.elu_backward.default: torchbench_train/nvidia_deeprecommender_training.json
aten.embedding.default: torchbench_train/BERT_pytorch_training.json
aten.embedding_dense_backward.default: torchbench_train/BERT_pytorch_training.json
aten.eq.Scalar: torchbench_train/BERT_pytorch_training.json
aten.eq.Tensor: torchbench_train/timm_efficientdet_training.json
aten.erf.default: torchbench_train/fastNLP_Bert_training.json
aten.exp.default: torchbench_train/vision_maskrcnn_training.json
aten.fill_.Scalar: torchbench_train/vision_maskrcnn_training.json
aten.fill_.Tensor: torchbench_train/speech_transformer_training.json
aten.flip.default: torchbench_train/hf_Longformer_training.json
aten.floor.default: torchbench_train/vision_maskrcnn_training.json
aten.floor_divide.default: torchbench_train/timm_efficientdet_training.json
aten.fmod.Scalar: torchbench_train/fastNLP_Bert_training.json
aten.gather.default: torchbench_train/fambench_dlrm_training.json
aten.ge.Scalar: torchbench_train/vision_maskrcnn_training.json
aten.gelu.default: torchbench_train/timm_nfnet_training.json
aten.gelu_backward.default: torchbench_train/timm_nfnet_training.json
aten.grid_sampler_2d.default: torchbench_train/Super_SloMo_training.json
aten.grid_sampler_2d_backward.default: torchbench_train/Super_SloMo_training.json
aten.gt.Scalar: torchbench_train/BERT_pytorch_training.json
aten.gt.Tensor: torchbench_train/timm_efficientdet_training.json
aten.hardsigmoid.default: torchbench_train/mobilenet_v3_large_training.json
aten.hardsigmoid_backward.default: torchbench_train/mobilenet_v3_large_training.json
aten.hardswish.default: timm_train/levit_128_training.json
aten.hardswish_.default: torchbench_train/mobilenet_v3_large_training.json
aten.hardswish_backward.default: torchbench_train/mobilenet_v3_large_training.json
aten.hardtanh.default: timm_train/rexnet_100_training.json
aten.hardtanh_.default: torchbench_train/mobilenet_v2_training.json
aten.hardtanh_backward.default: torchbench_train/mobilenet_v2_training.json
aten.im2col.default: hf_train/YituTechConvBert_training.json
aten.im2col_backward.default: hf_train/YituTechConvBert_training.json
aten.index.Tensor: torchbench_train/fambench_dlrm_training.json
aten.index_add.default: torchbench_train/hf_BigBird_training.json
aten.index_add_.default: torchbench_train/hf_Longformer_training.json
aten.index_put.default: torchbench_train/fambench_dlrm_training.json
aten.index_put_.default: torchbench_train/vision_maskrcnn_training.json
aten.index_select.default: torchbench_train/fambench_dlrm_training.json
aten.isinf.default: torchbench_train/hf_Bart_training.json
aten.isnan.default: torchbench_train/hf_Bart_training.json
aten.le.Scalar: torchbench_train/vision_maskrcnn_training.json
aten.leaky_relu.default: torchbench_train/Super_SloMo_training.json
aten.leaky_relu_.default: torchbench_train/yolov3_training.json
aten.leaky_relu_backward.default: torchbench_train/Super_SloMo_training.json
aten.lift_fresh_copy.default: timm_train/cspdarknet53_training.json
aten.log2.default: torchbench_train/vision_maskrcnn_training.json
aten.logical_and_.default: torchbench_train/vision_maskrcnn_training.json
aten.lt.Scalar: torchbench_train/speech_transformer_training.json
aten.lt.Tensor: torchbench_train/hf_Bart_training.json
aten.masked_fill.Scalar: torchbench_train/BERT_pytorch_training.json
aten.masked_fill.Tensor: torchbench_train/hf_DistilBert_training.json
aten.masked_fill_.Scalar: torchbench_train/BERT_pytorch_training.json
aten.max.default: torchbench_train/vision_maskrcnn_training.json
aten.max.dim: timm_train/volo_d1_224_training.json
aten.max_pool2d_with_indices.default: torchbench_train/Super_SloMo_training.json
aten.max_pool2d_with_indices_backward.default: torchbench_train/Super_SloMo_training.json
aten.maximum.default: hf_train/OPTForCausalLM_training.json
aten.mean.default: torchbench_train/Super_SloMo_training.json
aten.mean.dim: torchbench_train/mobilenet_v3_large_training.json
aten.min.default: torchbench_train/vision_maskrcnn_training.json
aten.minimum.default: torchbench_train/vision_maskrcnn_training.json
aten.mm.default: torchbench_train/mobilenet_v3_large_training.json
aten.mse_loss.default: torchbench_train/Super_SloMo_training.json
aten.mse_loss_backward.default: torchbench_train/Super_SloMo_training.json
aten.mul.Scalar: torchbench_train/BERT_pytorch_training.json
aten.mul.Tensor: torchbench_train/mobilenet_v3_large_training.json
aten.mul_.Tensor: torchbench_train/timm_nfnet_training.json
aten.native_batch_norm.default: torchbench_train/mobilenet_v3_large_training.json
aten.native_batch_norm_backward.default: torchbench_train/mobilenet_v3_large_training.json
aten.native_group_norm.default: timm_train/poolformer_m36_training.json
aten.native_group_norm_backward.default: timm_train/poolformer_m36_training.json
aten.native_layer_norm.default: torchbench_train/timm_vision_transformer_training.json
aten.native_layer_norm_backward.default: torchbench_train/timm_vision_transformer_training.json
aten.ne.Scalar: torchbench_train/speech_transformer_training.json
aten.neg.default: torchbench_train/Super_SloMo_training.json
aten.new_empty.default: torchbench_train/vision_maskrcnn_training.json
aten.new_empty_strided.default: torchbench_train/pytorch_CycleGAN_and_pix2pix_training.json
aten.new_full.default: torchbench_train/vision_maskrcnn_training.json
aten.new_ones.default: torchbench_train/speech_transformer_training.json
aten.new_zeros.default: torchbench_train/pytorch_CycleGAN_and_pix2pix_training.json
aten.nll_loss_backward.default: hf_train/ElectraForCausalLM_training.json
aten.nll_loss_forward.default: hf_train/ElectraForCausalLM_training.json
aten.nonzero.default: torchbench_train/vision_maskrcnn_training.json
aten.norm.ScalarOpt_dim: torchbench_train/tts_angular_training.json
aten.pow.Scalar: hf_train/XLNetLMHeadModel_training.json
aten.pow.Tensor_Scalar: torchbench_train/hf_Albert_training.json
aten.reciprocal.default: torchbench_train/vision_maskrcnn_training.json
aten.reflection_pad2d.default: torchbench_train/pytorch_CycleGAN_and_pix2pix_training.json
aten.reflection_pad2d_backward.default: torchbench_train/pytorch_CycleGAN_and_pix2pix_training.json
aten.relu.default: torchbench_train/mobilenet_v3_large_training.json
aten.relu_.default: torchbench_train/mobilenet_v3_large_training.json
aten.remainder.Scalar: torchbench_train/timm_efficientdet_training.json
aten.repeat.default: torchbench_train/BERT_pytorch_training.json
aten.roll.default: timm_train/swin_base_patch4_window7_224_training.json
aten.round.default: torchbench_train/vision_maskrcnn_training.json
aten.rsqrt.default: torchbench_train/vision_maskrcnn_training.json
aten.rsub.Scalar: torchbench_train/Super_SloMo_training.json
aten.scatter.src: timm_train/volo_d1_224_training.json
aten.scatter_add.default: torchbench_train/fambench_dlrm_training.json
aten.scatter_add_.default: torchbench_train/timm_efficientdet_training.json
aten.select_backward.default: torchbench_train/Super_SloMo_training.json
aten.sgn.default: torchbench_train/Super_SloMo_training.json
aten.sigmoid.default: torchbench_train/timm_nfnet_training.json
aten.sigmoid_.default: torchbench_train/yolov3_training.json
aten.sigmoid_backward.default: torchbench_train/timm_nfnet_training.json
aten.silu.default: timm_train/gmixer_24_224_training.json
aten.silu_.default: torchbench_train/timm_efficientdet_training.json
aten.silu_backward.default: torchbench_train/timm_efficientdet_training.json
aten.sin.default: hf_train/XLNetLMHeadModel_training.json
aten.slice_backward.default: torchbench_train/fambench_dlrm_training.json
aten.split.Tensor: torchbench_train/shufflenet_v2_x1_0_training.json
aten.split_with_sizes.default: torchbench_train/vision_maskrcnn_training.json
aten.sqrt.default: torchbench_train/vision_maskrcnn_training.json
aten.stack.default: torchbench_train/Super_SloMo_training.json
aten.std.correction: torchbench_train/BERT_pytorch_training.json
aten.sub.Tensor: torchbench_train/Super_SloMo_training.json
aten.sum.SymInt: torchbench_train/mobilenet_v3_large_training.json
aten.sum.default: torchbench_train/mobilenet_v3_large_training.json
aten.sum.dim_IntList: torchbench_train/timm_resnest_training.json
aten.tanh.default: torchbench_train/pytorch_CycleGAN_and_pix2pix_training.json
aten.tanh_backward.default: torchbench_train/pytorch_CycleGAN_and_pix2pix_training.json
aten.threshold_backward.default: torchbench_train/mobilenet_v3_large_training.json
aten.topk.default: torchbench_train/vision_maskrcnn_training.json
aten.tril.default: torchbench_train/hf_Longformer_training.json
aten.triu.default: torchbench_train/speech_transformer_training.json
aten.unbind.int: torchbench_train/Super_SloMo_training.json
aten.unfold_backward.default: timm_train/eca_halonext26ts_training.json
aten.unsqueeze_.default: torchbench_train/hf_BigBird_training.json
aten.upsample_bicubic2d.vec: timm_train/crossvit_9_240_training.json
aten.upsample_bilinear2d.vec: torchbench_train/Super_SloMo_training.json
aten.upsample_bilinear2d_backward.vec: torchbench_train/Super_SloMo_training.json
aten.upsample_nearest2d.vec: torchbench_train/vision_maskrcnn_training.json
aten.upsample_nearest2d_backward.vec: torchbench_train/vision_maskrcnn_training.json
aten.var_mean.correction: timm_train/convnext_base_training.json
aten.where.self: torchbench_train/vision_maskrcnn_training.json
