# Workflow to automatically cleanup the nightly Docker images
# Only keep the latest 200 images that are tagged
name: Tritonbench Nightly Docker Cleanup
on:
  workflow_dispatch:
  schedule:
    # Automatically cleanup the nightly Docker images every 3 months
    - cron: '0 0 1 */3 *'

permissions:
  contents: read
  packages: write
  packages: delete  # Required for deleting packages

jobs:
  clean-push-docker:
    if: ${{ github.repository_owner == 'meta-pytorch' }}
    runs-on: linux.2xlarge
    environment: docker-s3-upload
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          owner: meta-pytorch
          package-name: tritonbench
          package-type: docker
          delete-only-untagged-versions: true
          token: ${{ secrets.TRITONBENCH_ACCESS_TOKEN }}
      - uses: actions/delete-package-versions@v4
        with:
          owner: meta-pytorch
          package-name: tritonbench
          package-type: docker
          min-versions-to-keep: 200
          token: ${{ secrets.TRITONBENCH_ACCESS_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
